trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'terraformaksdevclusterregistry1234.azurecr.io/myapp'
  imageTag: '$(Build.BuildId)'
  
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        mvn clean package
        docker build -t $(imageRepository):$(imageTag) .
        docker push $(imageRepository):$(imageTag)
      displayName: 'Build and push Docker image'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: '5db014fe-1501-4706-a3a2-e0fb1f0ecb10'
        azureResourceGroup: 'terraform-aks-dev'
        kubernetesCluster: 'terraform-aks-dev-cluster'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/DeploymentFiles/Deployment.yaml'
        containerRegistryType: 'Azure Container Registry'
        azureContainerRegistry: 'terraformaksdevclusterregistry1234'
        azureContainerRegistryType: 'Azure Resource Manager'
        imagePullSecrets: |
          [
            {
              "name": "myregistrykey"
            }
          ]
