trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'terraformaksdevclusterregistry1234.azurecr.io/java-app'
  imageTag: '$(Build.BuildId)'
  ACR_NAME: 'terraformaksdevclusterregistry1234'
  
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        mvn clean package
        docker login terraformaksdevclusterregistry1234.azurecr.io --username $(acruser) --password $(acrpassword)
        docker build -t $(imageRepository):$(imageTag) .
        docker push $(imageRepository):$(imageTag)
      displayName: 'Build and push Docker image'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Terraform_Connection'
        azureResourceGroup: 'terraform-aks-dev'
        kubernetesCluster: 'terraform-aks-dev-cluster'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/DeploymentFiles/Deployment.yaml'
        containerRegistryType: 'Azure Container Registry'
        azureContainerRegistry: 'terraformaksdevclusterregistry1234'
        azureContainerRegistryType: 'Azure Resource Manager'
        imagePullSecrets: |
          [
            {
              "name": "acr-secret"
            }
          ]
